<header role="banner" class="l-header">
  <div class="u-wrapper">
    <h1 class="l-header__heading"><a href="" title="" class="l-header__heading-link">Raid Class</a></h1>
    <section class="c-profile-control">
      <h1 class="c-profile-control__heading">Profile control</h1>
      <button class="c-profile-control__toggle">Accomp</button>
    </section><!-- /.c-profile-control -->
  </div><!-- /.u-wrapper -->
</header><!-- /.l-header -->