<header role="banner" class="l-header">
  <div class="u-wrapper">
    <h1 class="l-header__heading"><a href="" title="" class="l-header__heading-link">Raid Class</a></h1>
    <a href="#sidr" title="" class="c-sidr__toggle">Toggle navigation</a>
    <div class="c-sidr" id="sidr">
      <section class="c-profile-control">
        <h1 class="c-profile-control__heading">Profile control</h1>
        <button class="c-profile-control__toggle">Accomp</button>
      </section><!-- /.c-profile-control -->
      <nav class="" role="navigation">
        <ul>
          <li><a href="" title="">Nav Item</a></li>
          <li><a href="" title="">Nav Item</a></li>
        </ul>
      </nav>
    </div><!-- /.c-sidr -->
  </div><!-- /.u-wrapper -->
</header><!-- /.l-header -->