<nav role="navigation" class="c-navigation-category">
  <div class="u-wrapper">
    <h1 class="c-navigation-category__heading">Rogue</h1>
    <ul class="c-navigation-category__list">
      <li class="c-navigation-category__list-item c-navigation-category__list-item--assassination">
        <a href="" title="" class="c-navigation-category__link">Assassination</a>
      </li><!-- /.c-navigation-category__list-item -->
      <li class="c-navigation-category__list-item c-navigation-category__list-item--outlaw is-active">
        <a href="" title="" class="c-navigation-category__link">Outlaw</a>
      </li><!-- /.c-navigation-category__list-item -->
      <li class="c-navigation-category__list-item c-navigation-category__list-item--subtlety">
        <a href="" title="" class="c-navigation-category__link">Subtlety</a>
      </li><!-- /.c-navigation-category__list-item -->
    </ul><!-- /.c-navigation-category__list -->
  </div><!-- /.u-wrapper -->
</nav><!-- /.c-navigation-category -->