<nav class="c-spec-navigation">
  <h1 class="c-spec-navigation__class">Outlaw<span class="c-spec-navigation__class-name"> Rogue</span></h1>
  <ul class="c-spec-navigation__list">
    <li class="c-spec-navigation__list-item c-spec-navigation__list-item--overview is-current">
      <a href="" title="" class="c-spec-navigation__link">Overview</a>
    </li><!-- /.c-spec-navigation__list-item -->
    <li class="c-spec-navigation__list-item c-spec-navigation__list-item--rotation">
      <a href="" title="" class="c-spec-navigation__link">Rotation</a>
    </li><!-- /.c-spec-navigation__list-item -->
    <li class="c-spec-navigation__list-item c-spec-navigation__list-item--talents">
      <a href="" title="" class="c-spec-navigation__link">Talents</a>
    </li><!-- /.c-spec-navigation__list-item -->
    <li class="c-spec-navigation__list-item c-spec-navigation__list-item--glyphs">
      <a href="" title="" class="c-spec-navigation__link">Glyphs</a>
    </li><!-- /.c-spec-navigation__list-item -->
    <li class="c-spec-navigation__list-item c-spec-navigation__list-item--stats">
      <a href="" title="" class="c-spec-navigation__link">Stats</a>
    </li><!-- /.c-spec-navigation__list-item -->
    <li class="c-spec-navigation__list-item c-spec-navigation__list-item--addons">
      <a href="" title="" class="c-spec-navigation__link">Addons</a>
    </li><!-- /.c-spec-navigation__list-item -->
    <li class="c-spec-navigation__list-item c-spec-navigation__list-item--macros">
      <a href="" title="" class="c-spec-navigation__link">Macros</a>
    </li><!-- /.c-spec-navigation__list-item -->
    <li class="c-spec-navigation__list-item c-spec-navigation__list-item--tips">
      <a href="" title="" class="c-spec-navigation__link">Boss Tips</a>
    </li><!-- /.c-spec-navigation__list-item -->
    <li class="c-spec-navigation__list-item c-spec-navigation__list-item--bis">
      <a href="" title="" class="c-spec-navigation__link">BiS List</a>
    </li><!-- /.c-spec-navigation__list-item -->
    <li class="c-spec-navigation__list-item c-spec-navigation__list-item--forum">
      <a href="" title="" class="c-spec-navigation__link">Forum</a>
    </li><!-- /.c-spec-navigation__list-item -->
  </ul><!-- /.c-spec-navigation__list -->
</nav><!-- /.c-spec-navigation -->
<select class="c-spec-navigation__select js-fancy-select">
  <option>Overview</option>
  <option>Rotation</option>
  <option>Talents</option>
  <option>Glyphs</option>
  <option>Stats</option>
  <option>Addons</option>
  <option>Macros</option>
  <option>Boss Tips</option>
  <option>BiS List</option>
  <option>Forum</option>
</select><!-- /.c-spec-navigation__select -->