<nav class="c-category-navigation">
  <div class="u-wrapper">
    <h1 class="c-category-navigation__heading">Rogue</h1>
    <ul class="c-category-navigation__list">
      <li class="c-category-navigation__list-item c-category-navigation__list-item--assassination">
        <a href="" title="" class="c-category-navigation__link">Assassination</a>
      </li><!-- /.c-category-navigation__list-item -->
      <li class="c-category-navigation__list-item c-category-navigation__list-item--outlaw is-active">
        <a href="" title="" class="c-category-navigation__link">Outlaw</a>
      </li><!-- /.c-category-navigation__list-item -->
      <li class="c-category-navigation__list-item c-category-navigation__list-item--subtlety">
        <a href="" title="" class="c-category-navigation__link">Subtlety</a>
      </li><!-- /.c-category-navigation__list-item -->
    </ul><!-- /.c-category-navigation__list -->
  </div><!-- /.u-wrapper -->
</nav><!-- /.c-category-navigation -->