<nav role="navigation" class="c-navigation-primary">
    <h1 class="c-navigation-primary__heading">Primary navigation</h1>
    <ul class="c-navigation-primary__list">
      <li class="c-navigation-primary__list-item c-navigation-primary__list-item--home">
        <a href="" title="" class="c-navigation-primary__link">Home</a>
      </li><!-- /.c-navigation-primary__list-item -->
      <li class="c-navigation-primary__list-item c-navigation-primary__list-item--blog">
        <a href="" title="" class="c-navigation-primary__link">Blog</a>
      </li><!-- /.c-navigation-primary__list-item -->
      <li class="c-navigation-primary__list-item c-navigation-primary__list-item--guides is-current">
        <a href="" title="" class="c-navigation-primary__link">Guides</a>
      </li><!-- /.c-navigation-primary__list-item -->
      <li class="c-navigation-primary__list-item c-navigation-primary__list-item--forums">
        <a href="" title="" class="c-navigation-primary__link">Forums</a>
      </li><!-- /.c-navigation-primary__list-item -->
    </ul><!-- /.c-navigation-primary__list -->
</nav><!-- /.c-navigation-primary -->