<nav role="navigation" class="c-navigation-section">
  <a href="" title="" class="c-navigation-section__logo">Raid Class</a>
  <h1 class="c-navigation-section__class">Outlaw<span class="c-navigation-section__class-name"> Rogue</span></h1>
  <ul class="c-navigation-section__list">
    <li class="c-navigation-section__list-item c-navigation-section__list-item--overview is-current">
      <a href="" title="" class="c-navigation-section__link">Overview</a>
    </li><!-- /.c-navigation-section__list-item -->
    <li class="c-navigation-section__list-item c-navigation-section__list-item--stats">
      <a href="" title="" class="c-navigation-section__link">Stat Priority</a>
    </li><!-- /.c-navigation-section__list-item -->
    <li class="c-navigation-section__list-item c-navigation-section__list-item--rotation">
      <a href="" title="" class="c-navigation-section__link">Rotation</a>
    </li><!-- /.c-navigation-section__list-item -->
    <li class="c-navigation-section__list-item c-navigation-section__list-item--talents">
      <a href="" title="" class="c-navigation-section__link">Talents</a>
    </li><!-- /.c-navigation-section__list-item -->
    <li class="c-navigation-section__list-item c-navigation-section__list-item--glyphs">
      <a href="" title="" class="c-navigation-section__link">Glyphs</a>
    </li><!-- /.c-navigation-section__list-item -->
    <li class="c-navigation-section__list-item c-navigation-section__list-item--addons">
      <a href="" title="" class="c-navigation-section__link">Addons</a>
    </li><!-- /.c-navigation-section__list-item -->
    <li class="c-navigation-section__list-item c-navigation-section__list-item--macros">
      <a href="" title="" class="c-navigation-section__link">Macros</a>
    </li><!-- /.c-navigation-section__list-item -->
    <li class="c-navigation-section__list-item c-navigation-section__list-item--bis">
      <a href="" title="" class="c-navigation-section__link">BiS List</a>
    </li><!-- /.c-navigation-section__list-item -->
    <li class="c-navigation-section__list-item c-navigation-section__list-item--tips">
      <a href="" title="" class="c-navigation-section__link">Boss Tips</a>
    </li><!-- /.c-navigation-section__list-item -->
    <li class="c-navigation-section__list-item c-navigation-section__list-item--forum">
      <a href="" title="" class="c-navigation-section__link">Forum</a>
    </li><!-- /.c-navigation-section__list-item -->
  </ul><!-- /.c-navigation-section__list -->
</nav><!-- /.c-navigation-section -->
<select class="c-navigation-section__select js-fancy-select">
  <option>Overview</option>
  <option>Stat Priority</option>
  <option>Rotation</option>
  <option>Talents</option>
  <option>Glyphs</option>
  <option>Addons</option>
  <option>Macros</option>
  <option>BiS List</option>
  <option>Boss Tips</option>
  <option>Forum</option>
</select><!-- /.c-navigation-section__select -->